links = c('http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/01.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/02.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/03.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/04.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/05.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/06.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/07.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/08.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/09.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/10.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/11.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/12.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/13.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/14.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/15.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/16.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/17.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/18.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/19.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/20.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/21.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/22.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/23.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/24.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/25.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/26.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/27.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/28.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/29.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/30.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/31.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/32.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/33.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/34.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/35.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/36.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/37.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/38.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/39.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/40.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/41.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/42.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/43.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/44.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/45.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/46.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/47.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/48.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/49.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/50.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/51.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/52.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/53.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/54.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/55.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/56.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/57.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/58.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/59.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/60.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/61.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/62.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/63.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/64.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/65.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/66.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/67.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/68.html',
          'http://www.e-bestbooks.com/George_R.R._Martin/A_Clash_of_Kings/69.html')



dest = c(
  '/Users/aleksandr/Desktop/eda project 2/book2/page1.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page2.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page3.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page4.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page5.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page6.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page7.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page8.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page9.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page10.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page11.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page12.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page13.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page14.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page15.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page16.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page17.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page18.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page19.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page20.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page21.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page22.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page23.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page24.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page25.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page26.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page27.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page28.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page29.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page30.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page31.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page32.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page33.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page34.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page35.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page36.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page37.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page38.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page39.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page40.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page41.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page42.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page43.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page44.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page45.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page46.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page47.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page48.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page49.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page50.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page51.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page52.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page53.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page54.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page55.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page56.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page57.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page58.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page59.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page60.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page61.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page62.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page63.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page64.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page65.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page66.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page67.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page68.html',
  '/Users/aleksandr/Desktop/eda project 2/book2/page69.html')


for(i in 1:length(links)){
  download.file(links, dest, mode="wb")}